#include "mousemotionlab/mousegen_runtime.h"
#include <windows.h>
#include <bcrypt.h>
#include <cassert>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace {
template<class T> void write(std::ofstream& out,const T* values,std::size_t count){out.write(reinterpret_cast<const char*>(values),static_cast<std::streamsize>(sizeof(T)*count));}
std::string digest(const std::filesystem::path& path){BCRYPT_ALG_HANDLE a{};BCRYPT_HASH_HANDLE h{};DWORD os{},ds{},n{};assert(BCryptOpenAlgorithmProvider(&a,BCRYPT_SHA256_ALGORITHM,nullptr,0)>=0);assert(BCryptGetProperty(a,BCRYPT_OBJECT_LENGTH,reinterpret_cast<PUCHAR>(&os),sizeof(os),&n,0)>=0);assert(BCryptGetProperty(a,BCRYPT_HASH_LENGTH,reinterpret_cast<PUCHAR>(&ds),sizeof(ds),&n,0)>=0);std::vector<unsigned char> object(os),result(ds);assert(BCryptCreateHash(a,&h,object.data(),os,nullptr,0,0)>=0);std::ifstream in(path,std::ios::binary);std::vector<char> buffer(4096);while(in){in.read(buffer.data(),buffer.size());if(in.gcount())assert(BCryptHashData(h,reinterpret_cast<PUCHAR>(buffer.data()),static_cast<ULONG>(in.gcount()),0)>=0);}assert(BCryptFinishHash(h,result.data(),ds,0)>=0);BCryptDestroyHash(h);BCryptCloseAlgorithmProvider(a,0);static constexpr char hex[]="0123456789abcdef";std::string s;for(auto v:result){s+=hex[v>>4];s+=hex[v&15];}return s;}
std::filesystem::path fixture(bool zeroEndpoint=false){auto root=std::filesystem::temp_directory_path()/("mml-pca-test-"+std::to_string(GetCurrentProcessId()));std::filesystem::remove_all(root);std::filesystem::create_directories(root);std::ofstream out(root/"pca.bin",std::ios::binary);const char magic[8]={'M','M','L','P','C','A','1','\0'};const std::uint32_t c=21,o=7,n=1,k=1,m=1,p=3;const double temperature=1,maximum=6;write(out,magic,8);write(out,&c,1);write(out,&o,1);write(out,&n,1);write(out,&k,1);write(out,&m,1);write(out,&p,1);write(out,&temperature,1);write(out,&maximum,1);std::vector<double> zeros(c,0),ones(c,1),training(c,0),output_mean{0,0,2,2,zeroEndpoint?0:.8,zeroEndpoint?0:.1,std::log(2e8)},output_scale(o,1),components(o,0),centers(c,0),latent_mean(1,0),latent_scale(1,0),prior(1,1);for(const auto* v:{&zeros,&ones,&training,&output_mean,&output_scale,&components,&centers,&latent_mean,&latent_scale,&prior})write(out,v->data(),v->size());out.close();std::ofstream manifest(root/"manifest.json");manifest<<"{\"schema_version\":1,\"format\":\"mousemotionlab-pca-mixture\",\"model_id\":\"synthetic-128-api\",\"files\":{\"pca.bin\":\""<<digest(root/"pca.bin")<<"\"}}\n";return root;}
MGGenerationRequest request(){MGGenerationRequest q{};q.start_x=-100;q.start_y=20;q.target_center_x=100;q.target_center_y=70;q.target_radius=24;q.virtual_desktop_left=-200;q.virtual_desktop_top=-100;q.virtual_desktop_width=500;q.virtual_desktop_height=300;q.dpi_scale=1;q.random_seed=42;q.endpoint_mode=MG_ENDPOINT_EXACT_CENTER;return q;}
}
int main(){auto root=fixture();MGHandle h{};assert(mg_create(root.string().c_str(),&h)==MG_OK);assert(std::string(mg_model_id(h))=="synthetic-128-api");assert(mg_position_count(h)==3);auto q=request();MGTrajectory a{},b{};assert(mg_generate(h,&q,&a)==MG_OK);assert(mg_generate(h,&q,&b)==MG_OK);assert(a.sample_count==3&&b.sample_count==3);assert(a.samples[0].x==q.start_x&&a.samples[0].y==q.start_y);assert(a.samples[2].x==q.target_center_x&&a.samples[2].y==q.target_center_y);for(std::size_t i=0;i<a.sample_count;++i){assert(a.samples[i].relative_time_ns==b.samples[i].relative_time_ns);assert(a.samples[i].x==b.samples[i].x&&a.samples[i].y==b.samples[i].y);assert(a.samples[i].x>=-200&&a.samples[i].x<=299&&a.samples[i].y>=-100&&a.samples[i].y<=199);}assert(a.endpoint_projected&&a.desktop_clipped_point_count>0);mg_free_trajectory(&a);mg_free_trajectory(&b);q.target_center_x=-200;q.target_center_y=-100;assert(mg_generate(h,&q,&a)==MG_OK);assert(a.samples[a.sample_count-1].x==-200&&a.samples[a.sample_count-1].y==-100);mg_free_trajectory(&a);q.target_center_x=q.start_x;q.target_center_y=q.start_y;assert(mg_generate(h,&q,&a)==MG_OK&&a.sample_count==0);mg_destroy(h);{std::ofstream corrupt(root/"pca.bin",std::ios::binary|std::ios::app);corrupt.put('x');}assert(mg_create(root.string().c_str(),&h)==MG_RUNTIME_ERROR);assert(std::string(mg_last_error(nullptr)).find("hash changed")!=std::string::npos);root=fixture(true);assert(mg_create(root.string().c_str(),&h)==MG_OK);q=request();assert(mg_generate(h,&q,&a)==MG_RUNTIME_ERROR);assert(std::string(mg_last_error(h)).find("too close to zero")!=std::string::npos);mg_destroy(h);std::filesystem::remove_all(root);}
